```{r}
library(nflreadr)
library(tidyverse)
library(brms)
library(ggthemes)
library(cmdstanr)
```

```{r}
load_participation(2021) -> partic #grab participation
load_pbp(2021) -> pbp #grab pbp
load_depth_charts(2021) -> depthchart #grab depth chart (for IDing QB runs)

partic |> 
  select(nflverse_game_id, play_id, offense_personnel, defenders_in_box) -> partic2

depthchart |> 
  select(gsis_id, depth_position) |> 
  rename(id = gsis_id) -> depthchart2

pbp |> 
  select(posteam, defteam, game_id, play_id, id, rush, epa, desc) |> 
  filter(!is.na(epa), rush == 1) -> pbp2 #just run plays

partic2 |> 
  rename(game_id = nflverse_game_id) |> 
  right_join(pbp2) -> pbp3

# This section is a mess, but I don't know regular expressions
# and this seemed like the most foolproof way to get the number
# and positions together without nonsense

pbp3 |> 
  mutate(item_1 = str_sub(offense_personnel, start = 0, end = 4),
         item_2 = str_sub(offense_personnel, start = 7, end = 10),
         item_3 = str_sub(offense_personnel, start = 13, end = 16),
         item_4 = str_sub(offense_personnel, start = 18, end = 22),
         item_5 = str_sub(offense_personnel, start = 24, end = 28)) -> pbp4



pbp4 |> 
  mutate (QB = case_when(str_detect(item_1, "QB") ~ 2,
            TRUE  ~ 1),
          OL = case_when(str_detect(item_1, "OL") & parse_number(item_1) == 6 ~ 6,
                         str_detect(item_2, "OL") & parse_number(item_2) == 6 ~ 6,
                         str_detect(item_1, "OL") & parse_number(item_1) == 7 ~ 7,
                         str_detect(item_2, "OL") & parse_number(item_2) == 7 ~ 7,
            TRUE  ~ 5),
          RB = case_when(str_detect(item_1, "RB") & parse_number(item_1) == 1 ~ 1,
                         str_detect(item_2, "RB") & parse_number(item_2) == 1 ~ 1,
                         str_detect(item_1, "RB") & parse_number(item_1) == 2 ~ 2,
                         str_detect(item_2, "RB") & parse_number(item_2) == 2 ~ 2,
                         str_detect(item_1, "RB") & parse_number(item_1) == 3 ~ 3,
                         str_detect(item_2, "RB") & parse_number(item_2) == 3 ~ 3,
            TRUE  ~ 0),
          
          TE = case_when(str_detect(item_2, "TE") & parse_number(item_2) == 1 ~ 1,
                         str_detect(item_3, "TE") & parse_number(item_3) == 1 ~ 1,
                         str_detect(item_4, "TE") & parse_number(item_4) == 1 ~ 1,
                         str_detect(item_2, "TE") & parse_number(item_2) == 2 ~ 2,
                         str_detect(item_3, "TE") & parse_number(item_3) == 2 ~ 2,
                         str_detect(item_4, "TE") & parse_number(item_4) == 2 ~ 2,
                         str_detect(item_2, "TE") & parse_number(item_2) == 3 ~ 3,
                         str_detect(item_3, "TE") & parse_number(item_3) == 3 ~ 3,
                         str_detect(item_4, "TE") & parse_number(item_4) == 3 ~ 3,
                         str_detect(item_2, "TE") & parse_number(item_2) == 4 ~ 4,
                         str_detect(item_3, "TE") & parse_number(item_3) == 4 ~ 4,
                         str_detect(item_4, "TE") & parse_number(item_4) == 4 ~ 4,
            TRUE  ~ 0),
          WR = case_when(str_detect(item_3, "WR") & parse_number(item_3) == 1 ~ 1,
                         str_detect(item_4, "WR") & parse_number(item_4) == 1 ~ 1,
                         str_detect(item_5, "WR") & parse_number(item_5) == 1 ~ 1,
                         str_detect(item_3, "WR") & parse_number(item_3) == 2 ~ 2,
                         str_detect(item_4, "WR") & parse_number(item_4) == 2 ~ 2,
                         str_detect(item_5, "WR") & parse_number(item_5) == 2 ~ 2,
                         str_detect(item_3, "WR") & parse_number(item_3) == 3 ~ 3,
                         str_detect(item_4, "WR") & parse_number(item_4) == 3 ~ 3,
                         str_detect(item_5, "WR") & parse_number(item_5) == 3 ~ 3,
                         str_detect(item_3, "WR") & parse_number(item_3) == 4 ~ 4,
                         str_detect(item_4, "WR") & parse_number(item_4) == 4 ~ 4,
                         str_detect(item_5, "WR") & parse_number(item_5) == 4 ~ 4,
                         str_detect(item_3, "WR") & parse_number(item_3) == 5 ~ 5,
                         str_detect(item_4, "WR") & parse_number(item_4) == 5 ~ 5,
                         str_detect(item_5, "WR") & parse_number(item_5) == 5 ~ 5,
              TRUE  ~ 0),
          DL = case_when(str_detect(item_3, "DL") & parse_number(item_3) == 1 ~ 1,
                         str_detect(item_4, "DL") & parse_number(item_4) == 1 ~ 1,
                         str_detect(item_5, "DL") & parse_number(item_5) == 1 ~ 1,
                         str_detect(item_3, "DL") & parse_number(item_3) == 2 ~ 2,
                         str_detect(item_4, "DL") & parse_number(item_4) == 2 ~ 2,
                         str_detect(item_5, "DL") & parse_number(item_5) == 2 ~ 2,
              TRUE  ~ 0),
          ) -> pbp5

# end "there must be a better way to do this" zone

pbp5 |> 
  left_join(depthchart2) |> 
  distinct(game_id, play_id, .keep_all = T)-> pbp6

# special measures for QB runs (but not WR, I should add that in in the future)
# also removing the few plays with LBs. Maybe 10 real plays, but mostly punts

pbp6 |> 
  mutate(blockers = pmax(OL + TE + DL + RB - 1 + QB - 1, 5),
         blockers = if_else(depth_position == "QB" & QB == 1, blockers + 1, blockers)) |> 
  filter(str_detect(item_4, "LB", negate = TRUE),
         str_detect(item_5, "LB", negate = TRUE))-> pbp6

pbp6 |> 
  select(defenders_in_box, blockers, epa) |> 
  na.omit() -> pbp7

```


```{r}
# next step is standardizing the values/index

pbp7 |> 
  mutate(D = as.integer(defenders_in_box + 1 - min(defenders_in_box)),
         B = as.integer(blockers + 1 - min(blockers)),
         epa = (epa - mean(epa)) / sd(epa)) -> pbp8 




bf_blockers <- bf(B ~ 1) + cumulative() #bounded count
bf_defenders <- bf(D ~ 1 + mo(B)) + cumulative() #bounded count
bf_epa <- bf(epa ~ mo(B) + mo(D)) + student() #why not a student_t

get_prior(data = pbp8, formula = bf_blockers + bf_defenders + bf_epa)

#Yes, I didn't set priors. 
#The defaults work fine here, but it would probably go way faster and
#be way more robust if I set them all properly

b12.7 <- 
  brm(data = pbp8, 
      bf_blockers + bf_defenders + bf_epa,
      prior = c(prior(normal(0, 1.5), class = Intercept),
                prior(normal(0, 1), class = b)),
                # note the new kinds of prior statements
      iter = 2000, warmup = 1000, cores = 4, chains = 4,
      seed = 12, backend="cmdstanr", stan_model_args=list(stanc_options = list("O1")),
      file = "~/b12.07")
```


```{r}
# Now we need a data set with all the blocker-defender combinations

min(pbp8$B)
max(pbp8$B)
min(pbp8$D)
max(pbp8$D)

tibble(B = rep(seq(1:6), 6), D = rep(seq(1:9), 4)) -> sim_data
sim_data |> 
  complete(B, D) -> sim_data2

# and then do some fitting to the simulated data

fitted(b12.7, newdata = sim_data2) |> as_tibble(.name_repair = "minimal") -> sim_data3

sim_data3 |> 
  select(contains("epa")) |> 
  bind_cols(sim_data2) |> 
  mutate(B = B + 4, # we subtracted these out earlier when we standardized
         D = D + 2) |> # so we add them back now
  rename(upper_est = Q97.5.epa, #gotta respect uncertainty
         lower_est = Q2.5.epa) |> 
  # and now we unstandardized everything
  mutate(Estimate.epa = (Estimate.epa + mean(pbp6$epa)) * sd(pbp6$epa),
         upper_est = (upper_est + mean(pbp6$epa)) * sd(pbp6$epa),
         lower_est = (lower_est + mean(pbp6$epa)) * sd(pbp6$epa))-> sim_data4

```

```{r}
# There's probably a better way to do this too

labels <- c(
                    '3' = "Defenders in the box = 3",
                    '4' = "Defenders in the box = 4",
                    "5" = "Defenders in the box = 5",
                    "6" = "Defenders in the box = 6",
                     "7" = "Defenders in the box = 7",
                      "8" = "Defenders in the box = 8",
                      "9" = "Defenders in the box = 9",
                      "10" = "Defenders in the box = 10",
                      "11" = "Defenders in the box = 11"
                    )

labels_b <- c(
                    "5" = "Blockers = 5 (5 OL)",
                    "6" = "Blockers = 6 (5 OL + TE/FB)",
                     "7" = "Blockers = 7 (Ace / I formation) ",
                      "8" = "Blockers = 8 (3 TE)",
                      "9" = "Blockers = 9 (Goaline)",
                      "10" = "Blockers = 10 (QB sneak/dive)"
                    )

```


```{r}
#graphs 

sim_data4 |> 
  ggplot(aes(x = B, y = Estimate.epa)) +
  geom_point() +
  geom_point(data = subset(sim_data4, B == D), color = "green") +
  geom_point(aes(y = upper_est), alpha = 0.2) +
  geom_point(aes(y = lower_est), alpha = 0.2) +
  geom_segment( aes(x = B, xend = B, y=lower_est, yend=upper_est), alpha = 0.2) +
  geom_hline(yintercept = 0) +
  facet_wrap(~D, labeller = as_labeller(labels)) +
  theme_solarized() +
  labs(x = "Blockers", y = "Estimated EPA",
       title = "Is adding a blocker worth it?",
       subtitle = "No, unless you're going up to 9 (5 OL + 3 TE + FB) or 10 blockers (QB sneak/dive)",
       caption = "Data: @nflfastR | Plot: @jonas_trostle@mastodon.online \n Blockers is OL + TE + RB + QB - 2 (except for QB runs, in which case we only subtract 1)")

sim_data4 |> 
  ggplot(aes(x = D, y = Estimate.epa)) +
  geom_point() +
  geom_point(aes(y = upper_est), alpha = 0.2) +
  geom_point(aes(y = lower_est), alpha = 0.2) +
  geom_segment( aes(x = D, xend = D, y=lower_est, yend=upper_est), alpha = 0.2) +
  geom_hline(yintercept = 0) +
    geom_point(data = subset(sim_data4, B == D), color = "green") +
  facet_wrap(~B, labeller = as_labeller(labels_b)) +
  theme_solarized() +
  labs(x = "Defenders in the box", y = "Estimated rush EPA",
       title = "Is adding a blocker worth it?",
       subtitle = "Not unless you're going up to 9 (5 OL + 3 TE + FB) or 10 blockers (QB sneak/dive)",
       caption = "Data: @nflfastR | Plot: @jonas_trostle@mastodon.online \n Blockers is OL + TE + RB + QB - 2 (except for QB runs, in which case we only subtract 1)") +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 8)) -> blockers_image_1

ggsave(filename = "blockers_image_1.png", blockers_image_1, height = 9, width = 16, dpi = "retina")

stancode(b12.7)
```

